apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: emoji-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emoji
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: response_per_second
        target:
          type: AverageValue
          averageValue: 1
