prometheus:
  url: http://prometheus.linkerd-viz.svc
  port: 9090
  path: ""

rules:
  custom:
  - seriesQuery: 'response_latency_ms_bucket{namespace!="",pod!=""}'
    resources:
      template: '<<.Resource>>'
    name:
      matches: '^(.*)_bucket$'
      as: "${1}_99th"
    metricsQuery: 'histogram_quantile(0.99, sum(irate(<<.Series>>{<<.LabelMatchers>>, direction="inbound", deployment!="", namespace!=""}[5m])) by (le, <<.GroupBy>>))'
